name: Publish an NPM Package

on:
  workflow_call:
    inputs:
      working-directory:
        description: Directory with the NPM package contnts
        type: string
        default: ./
        required: false
      build-command:
        description: Command to perform NPM pack
        type: string
        required: true
      ref:
        description: 'ref or tag to publish NPM package from'
        type: string
        required: false
      node-version:
        description: Node Version
        type: string
        default: 16.x
        required: false

    secrets:
      token:
        description: NPM token
        required: true

    outputs:
      package-name:
        description: Package name from package.json
        value: ${{ jobs.publish.outputs.package-name }}
      package-version:
        description: Package version
        value: ${{ jobs.publish.outputs.package-version }}
      published:
        description: Package has been published true/false
        value: ${{ jobs.publish.outputs.published }}
      status:
        description: Publishing failed/succeeded
        value: ${{ jobs.publish.outputs.status }}

jobs:
  publish:
    name: Build NPM package
    runs-on: ubuntu-latest
    outputs:
      package-version: ${{ steps.info.outputs.version }}
      package-name: ${{ steps.info.outputs.name }}
      published: ${{ steps.status.outputs.published }}
      status: ${{ steps.status.outputs.status }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
      -
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://registry.npmjs.org'
      -
        name: Package info
        id: info
        uses: gregoranders/nodejs-project-info@v0.0.12
        with:
          path: ${{ inputs.working-directory }}/package.json
      -
        name: Build package
        id: build
        working-directory: ${{ inputs.working-directory }}
        run: |
          ${{ inputs.build-command }}
      -
        name: Publish to npmjs.com
        working-directory: ${{ inputs.working-directory }}
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.token }}
      -
        name: Publish status
        id: status
        if: always()
        uses: actions/github-script@v5
        with:
          script: |
            core.setOutput('published', '${{ job.status == 'success' }}')
            if (${{ job.status == 'success' }}) {
              core.setOutput('status', 'succeeded')
            } else if (${{ job.status == 'failure' }}) {
              core.setOutput('status', 'failed')
            }
